[package]
name = "hex_spell"
version = "0.1.1"
authors=["Mestre <namestre3@protonmail.com>"]
edition = "2021"
description = "A open source lib to parse executables in Rust"
license = "MIT"
repository = "https://github.com/M3str3/Runic"

[dependencies]
thiserror = "1.0"

[dev-dependencies]
toml = "0.8.12"
