[package]
name = "hex_spell"
version = "0.1.5"
authors=["Mestre <namestre3@protonmail.com>"]
edition = "2021"
description = "Moved to 'hexspell' "
license = "MIT"
repository = "https://github.com/M3str3/HexSpell"
readme = "README.md"
exclude = ["tests/*"]
keywords = ["binary", "executable", "parser", "PE", "ELF" ]
categories = ["development-tools", "parsing"]

[dev-dependencies]
toml = "0.8.12"
