name: HexSpell testing

on:
  push:
    branches:
      - '*'  
  pull_request:
    branches:
      - '*'  

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, beta] 
        os: [ubuntu-latest, macos-latest, windows-latest]  

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal  # Use minimal profile for faster setup
        toolchain: ${{ matrix.rust }}  

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    - name: Build project
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose --all-features
